apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - etcd
                topologyKey: kubernetes.io/hostname
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.8
          command: ["etcd"]
          args:
            - "--advertise-client-urls=http://etcd:2379"
            - "--listen-client-urls=http://0.0.0.0:2379"
          ports:
            - containerPort: 2379
          resources:
            limits:
              memory: "512Mi"
              cpu: "100m"
            requests:
              memory: "512Mi"
              cpu: "100m"
          volumeMounts:
            - name: etcd-data
              mountPath: /var/lib/etcd
      volumes:
        - name: etcd-data
          persistentVolumeClaim:
            claimName: etcd-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: etcd
spec:
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: etcd-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: etcd
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: etcd
  hostPath:
    path: /data/etcd-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: etcd
